name: Building Faster R CI

on:
  # workflow_dispatch:
  #   inputs:
  #     cache:
  #       description: 'A boolean value indicating whether packages should be cached from one to the other'
  #       required: true
  #       default: true
  #     cache-version:
  #       description: 'The version of the cache, change this from the default (1) to start over with a fresh cache. Ignored if cache: false'
  #       required: true
  #       default: 1
  #     extra-packages:
  #       description: 'Any extra packages to install outside of the packages listed in the dependencies'
  #     needs:
  #       description: 'Any extra Config/Needs fields which need to be included when installing dependencies'
  #     packages:
  #       description: 'Which package(s) to install.'
  #       default: 'deps::., any::sessioninfo'
  #     pak-version:
  #       description: 'Which pak version to use. Possible values are "stable", "rc" and "devel".'
  #       default: 'stable'
  #     working-directory:
  #       description: 'Using the working-directory keyword, you can specify the working directory of where "pkg_deps" command searches for dependencies in the "DESCRIPTION" file.'
  #       default: '.'
  #     dependencies:
  #       description: 'Types of dependencies to install. Must be an R expression. Note that it often needs to be quoted in YAML, see the README for details.'
  #       default: '"all"'
  #     upgrade:
  #       description: 'Whether to install the latest available versions of the dependencies. Must be an R expression. See the README for details if you need quoting.'
  #       default: 'FALSE'
  push:
    branches:
      - "R-test"

jobs:
  build:
    runs-on: ubuntu-latest
    container: bahadzie/alpine-r-pandoc:4.3.0
    steps:
      # - run: R --version

      - name: Set site library path
        run: |
          # Set site library path
          cat("::group::Set site library path\n")
          if (Sys.getenv("RENV_PROJECT") != "") {
            message("renv project detected, no need to set R_LIBS_SITE")
            cat(sprintf("R_LIB_FOR_PAK=%s\n", .libPaths()[1]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            q("no")
          }
          lib <- Sys.getenv("R_LIBS_SITE")
          if (lib == "") {
            lib <- file.path(dirname(.Library), "site-library")
            cat(sprintf("R_LIBS_SITE=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            cat(sprintf("R_LIB_FOR_PAK=%s\n", lib), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
            message("Setting R_LIBS_SITE to ", lib)
          } else {
            message("R_LIBS_SITE is already set to ", lib)
            cat(sprintf("R_LIB_FOR_PAK=%s\n", strsplit(lib, .Platform$path.sep)[[1]][[1]]), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          }
          cat("::endgroup::\n")
        shell: Rscript {0}

      - name: Install pak (Unix)
        if: runner.os != 'Windows'
        run: |
          # Install pak
          cat("::group::Install pak\n")
          dir.create(Sys.getenv("R_LIB_FOR_PAK"), recursive = TRUE, showWarnings = FALSE)
          install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s",  .Platform$pkgType,  R.Version()$os,  R.Version()$arch), lib = Sys.getenv("R_LIB_FOR_PAK"))
          cat("::endgroup::\n")
        shell: Rscript {0}

      # - name: Install pak (Windows)
      #   if: runner.os == 'Windows'
      #   run: |
      #     # Install pak
      #     cat("::group::Install pak\n")
      #     lib <- Sys.getenv("R_LIB_FOR_PAK")
      #     dir.create(lib, showWarnings = FALSE, recursive = TRUE)
      #     install.packages("pak", repos = "https://r-lib.github.io/p/pak/${{ inputs.pak-version }}/", lib = lib)
      #     cat("::endgroup::\n")
      #   shell: Rscript {0}

      - name: Install RMarkdown
        run: |
          pak::pak("any::rmarkdown")
        shell: Rscript {0}


    # steps:
    #   -
    #     name: Checkout
    #     uses: actions/checkout@v3
    #   -
    #     name: Login to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #   -
    #     name: Set up Docker Buildx
    #     uses: docker/setup-buildx-action@v2
    #   -
    #     name: Build and push
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/alpine-r-pandoc:4.3.0


# name: 🎨 Test Visual Regression

# on: workflow_call

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     container: drizzt99/vonage:1.2.0
#     steps:
#       - run: echo "Running 1.2.0"

#       - uses: actions/checkout@v3

#       - uses: actions/setup-node@v3
#         with:
#           node-version: '16'
#           cache: 'npm'

#       - run: apt-get install tar -y

#       - uses: actions/cache@v3
#         id: cache
#         with:
#           path: node_modules/
#           key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

#       - name: Install Dependencies
#         if: steps.cache.outputs.cache-hit != 'true'
#         run: npm ci

#       - run: npm run nx e2e components -- --task=local
#       - uses: actions/upload-artifact@v3
#         with:
#           name: visual-regression-artifact
#           path: test-results/