# Update using https://docs.docker.com/build/ci/github-actions/push-multi-registries/
name: Build Docker R image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

# To be able to cancel a job in progress if the workflow file is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU # Required for build linux/arm64
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64 # comment out when commenting out QEMU step
          file: ./Dockerfile
          # push: true
          cache-from: type=gha # for cacheing build layers between builds
          cache-to: type=gha,mode=max # for cacheing build layers between builds
          outputs: type=tar,dest=/tmp/test_img.tar # output a local file that can be cached
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-r:4.3.0

      - uses: actions/upload-artifact@v3
        with:
          name: alpine-r430
          path: tmp/test_img.tar

      - name: List uploaded files
        run: |
          ls -al /tmp/t*